# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('off', '0003_auto_20180522_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='location',
            new_name='category',
        ),
    ]
